# Generated by Django 4.0.6 on 2022-07-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_turns', '0002_sickness_alter_doctor_status_alter_visit_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sickness',
            new_name='Services',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='subject',
            new_name='service',
        ),
    ]
