# Generated by Django 4.1.7 on 2023-02-19 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دکتر',
                'verbose_name_plural': 'دکترها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120, verbose_name='نام دسته')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='take_turns.services', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_persian', models.CharField(max_length=10)),
                ('hour', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_turns.services', verbose_name='گروه مراجعه')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vdoctor', to='take_turns.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'لیست نوبت ها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_persian', models.CharField(max_length=10)),
                ('from_hour', models.IntegerField()),
                ('to_hour', models.IntegerField()),
                ('interval_sick', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdoctor', to='take_turns.doctor')),
            ],
            options={
                'verbose_name': 'حضور دکتر',
                'verbose_name_plural': 'تاریخ و ساعت حضور دکتر',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_turns.services', verbose_name='گروه کاری'),
        ),
    ]
