# Generated by Django 4.0.6 on 2023-02-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_turns', '0002_doctor_date_presence_date_visit_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-date'], 'verbose_name': 'دکتر', 'verbose_name_plural': 'دکترها'},
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-date'], 'verbose_name': 'حضور دکتر', 'verbose_name_plural': 'تاریخ و ساعت حضور دکتر'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-date'], 'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date'], 'verbose_name': 'نوبت', 'verbose_name_plural': 'صف نوبت'},
        ),
    ]
