# Generated by Django 4.0.5 on 2022-07-08 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='سریال')),
                ('melli', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کدملی')),
                ('username', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(max_length=500, verbose_name='نام کامل')),
                ('brithday', models.IntegerField(blank=True, null=True, verbose_name='سن')),
                ('place', models.CharField(blank=True, max_length=500, null=True, verbose_name='محل سکونت')),
                ('tel', models.CharField(max_length=20, verbose_name='موبایل')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('is_admin', models.BooleanField(default=False, verbose_name='کاربر ارشد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='1.jpg', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
