# Generated by Django 4.0.6 on 2022-09-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
