# Generated by Django 4.0.6 on 2023-02-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='melli',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='کدملی'),
        ),
    ]
