# Generated by Django 4.1.7 on 2023-02-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_images_parttake_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='', verbose_name='تصویر سایز اصلی'),
        ),
        migrations.AlterField(
            model_name='images',
            name='status_sms',
            field=models.BooleanField(blank=True, null=True, verbose_name='وضعیت ارسال پیامک'),
        ),
        migrations.AlterField(
            model_name='images',
            name='thumbnail',
            field=models.ImageField(default='1.jpg', upload_to='', verbose_name='تصویر سایز کوچک'),
        ),
    ]
