# Generated by Django 4.0.6 on 2023-02-07 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_melli'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'تصاویر', 'verbose_name_plural': 'تصویرها'},
        ),
        migrations.AddField(
            model_name='images',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
    ]
