# Generated by Django 4.0.6 on 2023-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_user_name_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reception',
            field=models.BooleanField(default=False, verbose_name='پذیرش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='melli',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کدملی'),
        ),
    ]
