# Generated by Django 4.0.6 on 2023-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_images_options_images_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='status_sms',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='thumbnail',
            field=models.ImageField(default='1.jpg', upload_to=''),
        ),
    ]
