# Generated by Django 4.1.7 on 2023-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_images_image_alter_images_status_sms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, verbose_name='آدرس کاربر'),
        ),
    ]
