# Generated by Django 4.0.6 on 2023-01-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_reception_alter_user_melli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_reception',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='پذیرش'),
        ),
    ]
