# Generated by Django 4.1.7 on 2023-02-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, null=True, verbose_name='آدرس کاربر'),
        ),
    ]
