# Generated by Django 4.1.7 on 2023-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.CharField(default='ایران', max_length=200, verbose_name='محل سکونت'),
        ),
    ]
