# Generated by Django 4.0.6 on 2023-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='msgId_sms',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سریال پیامک ارسالی'),
        ),
    ]
