# Generated by Django 4.0.6 on 2023-03-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_images_msgid_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت ارسال پیامک'),
        ),
    ]
