# Generated by Django 4.0.6 on 2023-03-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_images_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='cost',
            new_name='cost_sms',
        ),
    ]
