# Generated by Django 4.0.6 on 2023-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_cost_images_cost_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='cost_sms',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='قیمت ارسال پیامک'),
        ),
    ]
