# Generated by Django 4.1.7 on 2023-02-18 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True, verbose_name='عنوان سوال')),
                ('op1', models.CharField(max_length=200, null=True, verbose_name='گزینه 1')),
                ('op2', models.CharField(max_length=200, null=True, verbose_name='گزینه 2')),
                ('op3', models.CharField(max_length=200, null=True, verbose_name='گزینه 3')),
                ('op4', models.CharField(max_length=200, null=True, verbose_name='گزینه 4')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'پرسش ها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=200, null=True, verbose_name='گزینه انتخاب شده')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='suggestions.quesmodel', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ دهنده')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
                'ordering': ['-date'],
            },
        ),
    ]
