# Generated by Django 4.0.6 on 2023-01-15 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True)),
                ('op1', models.CharField(max_length=200, null=True, verbose_name='گزینه 1')),
                ('op2', models.CharField(max_length=200, null=True, verbose_name='گزینه 2')),
                ('op3', models.CharField(max_length=200, null=True, verbose_name='گزینه 3')),
                ('op4', models.CharField(max_length=200, null=True, verbose_name='گزینه 4')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
        ),
    ]
