# Generated by Django 4.0.6 on 2023-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='ans_op1',
            field=models.IntegerField(null=True, verbose_name='تعدادانتخاب گزینه op1'),
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='ans_op2',
            field=models.IntegerField(null=True, verbose_name='تعدادانتخاب گزینه op2'),
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='ans_op3',
            field=models.IntegerField(null=True, verbose_name='تعدادانتخاب گزینه op3'),
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='ans_op4',
            field=models.IntegerField(null=True, verbose_name='تعدادانتخاب گزینه op4'),
        ),
    ]
