# Generated by Django 4.0.6 on 2023-01-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_remove_quesmodel_ans_op1_remove_quesmodel_ans_op2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultmodel',
            name='ans_op1',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='ans_op2',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='ans_op3',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='ans_op4',
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='ans',
            field=models.CharField(max_length=200, null=True, verbose_name='گزینه انتخاب شده'),
        ),
    ]
