# Generated by Django 4.1.7 on 2023-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0006_alter_quesmodel_options_alter_resultmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(max_length=500, null=True, verbose_name='عنوان سوال'),
        ),
    ]
